os: windows

language: bash

group: dev

before_install:
  - env
  - choco list --local-only
  - choco uninstall nvs
  - choco info nvs
  - export NVS_HOME=$ProgramData/nvs
  - git clone https://github.com/jasongin/nvs $NVS_HOME
  - . $NVS_HOME/nvs.sh
  - where nvs
  - nvs add latest
