os: windows

language: bash

group: dev

before_install:
  - echo "--------------------------------------"
  - env
  - echo "--------------------------------------"
  - choco list --local-only
  - echo "--------------------------------------"
  - export NVS_HOME=$ProgramData/nvs
  - git clone --single-branch -b joshk-msys_nt https://github.com/joshk/nvs $NVS_HOME
  - . $NVS_HOME/nvs.sh
  - echo "--------------------------------------"
  - env
  - echo "--------------------------------------"
  - nvs add latest
  - nvs use latest
  - echo "--------------------------------------"
  - node --version
  - npm --version
  - echo "--------------------------------------"
  - git clone https://github.com/yargs/yargs
  - cd yargs
  - echo "--------------------------------------"
  - npm i -g npm@latest
  - npm install
  - node --version
  - npm --version
  - npm t
