os: windows

language: bash

group: dev

before_install:
  - env
  - choco list --local-only
  - choco uninstall nvs
  - choco install nvs
  - choco info nvs
  - ls -la /c/Users/travis/AppData/Local
  - ls -la /c/Users/travis/AppData/Local/nvs
  - export NVS_HOME=/c/Users/travis/AppData/Local/nvs
  - . $NVS_HOME/nvs.sh
  - where nvs
  - nvs add latest
